### ISSUE TITLE
Code cleanup throughout the code

### ISSUE THREAD

**Issue by pgroen** [TrueBrain/TrueMQTT-cpp#2]
While using the prefix `m_` for private member (Giggity) variables, you also use the `this->` pointer. Kinda redundant..?

**Comment by TrueBrain** [comment]
Additionally, the members in `Client::Impl` should receive a well deserved `m_` too.

**Comment by TrueBrain** [comment]
Fixed in 584030bec45c446202007c0af35ca8a081494c01
